name: Deploy Laravel to cPanel

on:
  push:
    branches:
      - main # or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CPANEL_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H mtwd-kit.ph >> ~/.ssh/known_hosts

      - name: Deploy to cPanel
        run: |
          ssh mtwdkit@mtwd-kit.ph << 'EOF'
            cd home/mtwdkit/mios.mtwd-kit.ph

            git pull origin main

            # Laravel specific commands
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan optimize:clear
            php artisan icons:cache
            php artisan filament:optimize
          EOF
